[common]
build_flags = 
    -Wno-psabi

[teensy_common]
build_flags =
    ${common.build_flags}
    -DUSB_SERIAL
    -I include
lib_deps =
    https://github.com/tonton81/FlexCAN_T4
    https://github.com/FastLED/FastLED
    SPI

[env:teensy]
platform = teensy
framework = arduino
board = teensy40
build_type = release
build_flags =
    ${teensy_common.build_flags}
    -I src

#build_src_filter =
#    +<src>
lib_deps =
    ${teensy_common.lib_deps}
